# Generated by Django 5.2.7 on 2025-10-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_youtubelink_sliderimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groom',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
