# Generated by Django 5.2.7 on 2025-10-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_bride_familymember_groom_sliderimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='family_type',
            field=models.CharField(choices=[('groom', "Groom's Family"), ('bride', "Bride's Family")], default='groom', max_length=10),
        ),
    ]
